import palette from './palette'

export default {
  initialColorMode: 'light',
  colors: {
    primary: palette.lightBlue,
    secondary: palette.yellow,
    text: '#4E5B6E',
    background: '#E8EAED',
    muted: palette.white,
    buttonBg: palette.black,
    buttonText: palette.yellow,
    borderColor: '#E5E9F2',
    subHeading: '#4E5B6E',
    detailLabel: '#4E5B6E',
    detailValue: palette.lightBlue,
    appBar: palette.black,
    link: palette.lightBlue,
    inputBg: '#EFF2F7',
    inputBorder: '#E5E9F2',
    inputColor: '#3C4858',
    error: '#DC143C',
    logo: palette.yellow,
    divider: palette.black,
    modes: {
      dark: {
        primary: palette.yellow,
        secondary: palette.lightBlue,
        text: '#abb1ba',
        background: palette.black,
        muted: '#333',
        buttonBg: palette.lightBlue,
        borderColor: '#3C4858',
        subHeading: palette.lightBlue,
        detailLabel: palette.lightBlue,
        detailValue: palette.yellow,
        appBar: '#333',
        inputBg: palette.white,
        inputBorder: '#3C4858',
        inputColor: '#273444',
        logo: palette.yellow,
        divider: '#999',
      },
    },
  },
  fonts: {
    body: 'Helvetica',
    heading: 'starwars',
    monospace: 'Menlo, monospace',
  },
  fontSizes: [16, 18, 20, 26, 32, 64, 72, 84],
  fontWeights: {
    body: 400,
    heading: 800,
  },
  lineHeights: {
    heading: 1,
    body: 1.2,
  },
  letterSpacings: {
    body: 0.1,
    heading: 1.2,
    button: 2,
  },
  space: [0, 4, 12, 16, 32, 64, 128, 256],
  radii: {
    default: 8,
    circle: 99999,
  },
  buttons: {
    primary: {
      fontSize: 3,
      fontFamily: 'heading',
      letterSpacing: 'button',
      color: 'buttonText',
      bg: 'buttonBg',
      borderRadius: 'default',
      cursor: 'pointer',
      px: 4,
      py: 2,
    },
    secondary: {
      variant: 'buttons.primary',
      fontSize: 1,
      px: 3,
    },
  },
  variants: {
    card: {
      bg: 'muted',
      color: 'text',
      border: '1px solid',
      borderRadius: 'default',
      borderColor: 'borderColor',
      overflow: 'hidden',
    },
    content: {
      width: [400, 600, 1000],
      bg: 'background',
      mx: 'auto',
      pt: '5',
      pb: '6',
    },
    fitContent: {
      variant: 'variants.container',
      maxwidth: '740px',
    },
  },
  text: {
    body: {
      fontSize: [2, 1, 0],
      fontFamily: 'body',
      lineHeight: 'body',
      letterSpacing: 'body',
    },
    heading: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'heading',
      letterSpacing: 'heading',
      color: 'primary',
    },
    h1: {
      variant: 'text.heading',
      fontSize: 4,
    },
    h2: {
      variant: 'text.heading',
      fontSize: [4, 4, 3],
      py: 3,
    },
    h3: {
      variant: 'text.heading',
      fontSize: 1,
    },
    sub: {
      fontSize: 3,
      color: 'subHeading',
    },
    logo: {
      small: {
        variant: 'text.heading',
        color: 'logo',
        fontSize: 4,
      },
      large: {
        variant: 'text.heading',
        color: 'logo',
        fontSize: 7,
      },
    },
    link: {
      variant: 'text.body',
      color: 'link',
      cursor: 'pointer',
    },
    error: {
      variant: 'text.body',
      color: 'error',
      fontSize: 2,
    },
  },
}
